### ISSUE TITLE
Toolbar dont update on request and break display of queries

### ISSUE THREAD

**Issue by aldarund** [flavors/django-graphiql-debug-toolbar#1]
After load of graphql a lot of data appears in the response screen which not supposed to be there.
And if run any query - output in response screen will be escaped.
https://i.imgur.com/UEoEuEK.gifv

PS in the docs there some steps are missed.
1) Add local ip to INTERNAL_IPS -  Without it toolbar dont show up at all.
2) add urls from debug toolbar to urls.py is missed. Without it there will be a error

**Comment by mongkok** [comment]
Hi @aldarund,
Is there any error in Javascript debug console?
could you send me information about the environment?
- Django version
- Graphene-django version
- Debug-toolbar version

and thanks for the suggestion, I should include in the README the installation steps or a link to the [debug-toolbar docs](https://django-debug-toolbar.readthedocs.io/en/stable/installation.html#getting-the-code).

**Comment by aldarund** [comment]
@mongkok 
in chrome console:
[Violation] Added non-passive event listener to a scroll-blocking <some> event. Consider marking event handler as 'passive' to make the page more responsive. See <URL>
![image](https://user-images.githubusercontent.com/571159/37475657-41020ddc-2884-11e8-817b-437fbe81a846.png)

In firefox console only warning about window.content vs window.top. But ff behave same.

django 2.0.3
graphene-django 2.0.0
debug-toolbar 1.9.1
python 3.6.4

(basically just the last versions of everything)

**Comment by mongkok** [comment]
Thanks @aldarund,
Same warnings and environment here, but it works.
I recently created a new release, I think it could fix the issue.
```sh
pip install django-graphiql-debug-toolbar==0.0.2
```

If it does not work, I have updated a howtographql layout with django-graphiql-debug-toolbar
https://github.com/mongkok/graphql-python/tree/debug-toolbar

**Comment by aldarund** [comment]
@mongkok 0.0.2 works fine

**Comment by ckeeney** [comment]
I'm having this same problem on version `0.1.3`.

```
Django==2.1.5
django-debug-toolbar==1.11
django-graphiql-debug-toolbar==0.1.3
graphene-django==2.2.0

Python 3.6.5
```

I can open another issue, but all the symptoms are the same.  There is a query result that looks to be a schema dump in the GraphiQL response panel upon initial load, and executing queries results in unescaped responses in the GraphiQL response panel.

**Comment by ckeeney** [comment]
The issue eventually went away after i refreshed a few times in and out of incognito mode.  Maybe it is a caching issue somewhere.
