### ISSUE TITLE
Time Field in debug toolbar not updated on graphsql request

### ISSUE THREAD

**Issue by aldarund** [flavors/django-graphiql-debug-toolbar#3]

**Comment by mongkok** [comment]
CPU time, browser timing, title, content...?
Could you describe the issue?

Thanks.

**Comment by aldarund** [comment]
Request time.
https://i.imgur.com/U5EC1HE.png

**Comment by mongkok** [comment]
thanks for the screenshot @aldarund, the time panel on win systems has no content and the JS selector doesn't work.

I'll create a new release to fix it at the end of the day.

**Comment by mongkok** [comment]
Hi @aldarund,
you can install version v0.1.0
```sh
pip install django-graphiql-debug-toolbar==0.1.0
```
