### ISSUE TITLE
Errors got eaten and instead meaningless JSONDecodeError error thrown

### ISSUE THREAD

**Issue by aldarund** [flavors/django-graphiql-debug-toolbar#4]
For example if i have a error in my code like this 
https://gist.github.com/aldarund/af6bdb1e7a63aa8e6f318df8a8cf38ef 
( normal stacktrace with debug-toolbar disabled)
debug toolbar hide this error and instead throw meaningless JsonEncoder error like this:
https://gist.github.com/aldarund/d7b97a923f4949b63f3d0b273dbb02c7 ( meaningless stacktrace with debugtoolbar enabled)

**Comment by mongkok** [comment]
Hi @aldarund,
this error is not caused by graphiql-debug-toolbar middleware, you could open an issue in debug-toolbar or graphene framework instead

**Comment by aldarund** [comment]
@mongkok how that? 

File "C:\Dev\PycharmProjects\hamachi_gql\venv\lib\site-packages\graphiql_debug_toolbar\middleware.py" in get_payload
  32.     payload = json.loads(get_content(response), object_pairs_hook=OrderedDict)


This is from graphsql debug toolbar. And this is what hides the actual error.

**Comment by mongkok** [comment]
yes, you are right, I removed the message... late.

**Comment by mongkok** [comment]
Fixed!,

```py
pip install django-graphiql-debug-toolbar==0.1.1
```
