### ISSUE TITLE
Django 2.2 Django-Debug-Toolbar 2.0 AttributeError: 'object has no attribute 'process_view'

### ISSUE THREAD

**Issue by bendog** [flavors/django-graphiql-debug-toolbar#6]
Followed the install instructions and I ended up with this error, I'm assuming it's a compatibility issue with DDT 2.0? 
```
Django Version: 2.2.3
django-debug-toolbar==2.0
AttributeError: 'object has no attribute 'process_view'
.venv/lib/python3.7/site-packages/graphiql_debug_toolbar/middleware.py in process_view, line 57
```

**Comment by hansek** [comment]
I met this issue as well, my temporary solution is to install DDT in last stable 1.x version before installing DGDT.

```
django-debug-toolbar==1.11
django-graphiql-debug-toolbar==0.1.3
```

**Comment by kikeh** [comment]
Yes, it is a compatibility issue with DDT 2.0, as they have removed the support for Django’s deprecated `MIDDLEWARE_CLASSES`.

Taking a quick look, it didn't seem trivial to upgrade `django-graphiql-debug-toolbar` middleware to Django's new style and keep it compatible with `django-debug-toolbar`'s middleware.

Let's hope @mongkok will give it a try anytime soon 😬

**Comment by mongkok** [comment]
Hey guys,
Sorry for the delay in my response.
I've created a new release `django-graphiql-debug-toolbar==0.1.4`.
